#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
#Testing my PR
# trigger: none
resources:
  pipelines:
  - pipeline: eshoponweb-ci-dockercompose
    source: eshoponweb-ci-dockercompose # given pipeline name
    trigger: true
  repositories:
    - repository: self
      trigger: none

variables:
  location: 'eastu'
  templateFile: '.azure/bicep/aci.bicep'
  subscriptionid: '86d7ce15-b2bf-4a5c-be7a-b1e8d8d62eb0'
  azureserviceconnection: 'azure subs'
  webappname: 'rg-az400-eshoponweb-camerosusana'
  acr-login-server: 'YOUR-ACR.azurecr.io'
  acr-username: 'ACR-USERNAME'
  resource-group: 'rg-az400-eshoponweb-camerosusana' 


stages:
- stage: Deploy
  displayName: Docker Compose to ACI
  #variable group referencing KV secret
  variables:
  - group: 'eshopweb-vg'
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Deploy Azure Container Instance using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACI Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: ' -name $(webappname) -image $(acr-login-server)/eshopwebmvc:latest -server $(acr-login-server) -username $(acr-username) -password $(acr-secret)'
        deploymentMode: 'Incremental'
        # deploymentOutputs: 'asp-json'
    
